package step_definitions;

import io.cucumber.java.After;
import io.cucumber.java.AfterStep;
import io.cucumber.java.Before;
import io.cucumber.java.Scenario;
import utilities.CommonMethods;
import utilities.ConfigReader;
import utilities.DriverUtilities;

import java.sql.Driver;

public class Hooks {

    //11b. Add Before and After Hook methods
    @Before
    public void setUp(Scenario scenario){
        //Here we initialize the properties object inside of ConfigReader class that was created
        //we have to initialize properties first before we can use createDriver()
        ConfigReader.initializeProperties();
        DriverUtilities.createDriver(scenario);
    }

    @After
    public void tearDown(Scenario scenario){
        //Here we are using the scenario.attach() method to attach our screenshot to the scenario
        //the three parameters we are passing is the byte[] array screednshot which is generated by the takeScreenshot() method
        //the media type image/png since this is an image of png type
        //and the name of the scenario as the name of the image
        if(scenario.isFailed()) {
            scenario.attach(CommonMethods.takeScreenshot(), "image/png", scenario.getName());
        }
        CommonMethods.takeScreenshot(scenario);

        DriverUtilities.quitDriver(scenario);
    }
    @AfterStep
    public void stepPause() throws InterruptedException{
        Thread.sleep(1000);
    }

    //12a. Create pages package and BasePage class
}
